version: "3.8"
services:
  nestapi:
    environment:
      REDIS_HOST: redis
      DB_HOST: mysql
    container_name: chat_backend_nest
    build: .
    command: pnpm start:dev
    depends_on:
      - mysql
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: chat_redis
    ports:
      - '6379:6379'
    command:
      redis-server
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat
    container_name: chat_mysql
    ports:
      - '3306:3306'