version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: chat_redis
    ports:
      - '6379:6379'
    command:
      redis-server
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat
    container_name: chat_mysql
    ports:
      - '3306:3306'